//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlowCheetah.VisualStudio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SlowCheetah.VisualStudio.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the preview tool {0}. Verify the settings in the &apos;Config Transform&apos; category of Tools\Options..
        /// </summary>
        internal static string Error_CantFindPreviewTool {
            get {
                return ResourceManager.GetString("Error_CantFindPreviewTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No preview tool specified. You can set a preview tool in the &apos;Config Transform&apos; category of Tools\Options..
        /// </summary>
        internal static string Error_NoPreviewToolSpecified {
            get {
                return ResourceManager.GetString("Error_NoPreviewToolSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save the project file {0}. {1}.
        /// </summary>
        internal static string Error_SavingProjectFile {
            get {
                return ResourceManager.GetString("Error_SavingProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source file for the transform {0} was not found..
        /// </summary>
        internal static string Error_SourceFileNotFound {
            get {
                return ResourceManager.GetString("Error_SourceFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transform file {0} was not found..
        /// </summary>
        internal static string Error_TransformFileNotFound {
            get {
                return ResourceManager.GetString("Error_TransformFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error installing SlowCheetah NuGet package to {0}.\n.
        /// </summary>
        internal static string NugetInstall_ErrorOutput {
            get {
                return ResourceManager.GetString("NugetInstall_ErrorOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished installing SlowCheetah NuGet package to {0}.\n.
        /// </summary>
        internal static string NugetInstall_FinishedOutput {
            get {
                return ResourceManager.GetString("NugetInstall_FinishedOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing SlowCheetah NuGet package to {0} ...\n.
        /// </summary>
        internal static string NugetInstall_InstallingOutput {
            get {
                return ResourceManager.GetString("NugetInstall_InstallingOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to execute transform on build, you will need the SlowCheetah NuGet package. Do you want to install the package now?.
        /// </summary>
        internal static string NugetInstall_Text {
            get {
                return ResourceManager.GetString("NugetInstall_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install SlowCheetah NuGet package.
        /// </summary>
        internal static string NugetInstall_Title {
            get {
                return ResourceManager.GetString("NugetInstall_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        internal static string NugetUpdate_InfoBarLink {
            get {
                return ResourceManager.GetString("NugetUpdate_InfoBarLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems that you do not have the correct version of the SlowCheetah Nuget package installed. Transforms on this project will not be executed. To learn about updating from an older version, click .
        /// </summary>
        internal static string NugetUpdate_InfoBarText {
            get {
                return ResourceManager.GetString("NugetUpdate_InfoBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/sayedihashimi/slow-cheetah/blob/master/doc/update.md.
        /// </summary>
        internal static string NugetUpdate_Link {
            get {
                return ResourceManager.GetString("NugetUpdate_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1}{2}.
        /// </summary>
        internal static string String_FormatTransformFilename {
            get {
                return ResourceManager.GetString("String_FormatTransformFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!-- For more information on using transformations 
        ///     see the web.config examples at http://go.microsoft.com/fwlink/?LinkId=214134. --&gt;
        ///.
        /// </summary>
        internal static string TransformContents {
            get {
                return ResourceManager.GetString("TransformContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Preview.
        /// </summary>
        internal static string TransformPreview_Caption {
            get {
                return ResourceManager.GetString("TransformPreview_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original {0}.
        /// </summary>
        internal static string TransformPreview_LeftLabel {
            get {
                return ResourceManager.GetString("TransformPreview_LeftLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformed {0}   (by  {1} ).
        /// </summary>
        internal static string TransformPreview_RightLabel {
            get {
                return ResourceManager.GetString("TransformPreview_RightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Preview.
        /// </summary>
        internal static string TransformPreview_ToolTip {
            get {
                return ResourceManager.GetString("TransformPreview_ToolTip", resourceCulture);
            }
        }
    }
}
